### ISSUE TITLE
`ui-lock-choice` for multiple select makes items unremovable after unlocking

### ISSUE THREAD

**Issue by Mugi4ok** [angular-ui/ui-select#1878]
### Bug description: 
While using `ui-lock-choice` attribute inside `ui-select-match` for `multiple` `ui-select` after I lock and then unlock choices, all choices selected **prior** to locking become unremovable, clicking on `x` just does nothing. 
This does not affect elements added after locking *or* all elements before locking ever applied, although repeated lock-unlock action makes them unremovable as well.
Bug reproduces since 0.18.1 till latest version (last working version is 0.17.1 as I tested).

Steps to reproduce:
1. Select some elements from multiple select box, try removing them - should behave as expected;
2. Lock choices for this select box; then unlock it;
3. Try to remove previously added elements - elements are not removed; 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/KvDDll8h2wZg7JUJuWae?p=preview - use checkbox on top for lock/unlock

### Version of Angular, UI-Select, and Bootstrap/Select2/Selectize CSS

Angular: 1.4.9 *or* version used in Plunker demo

UI-Select: >=0.18.1

Bootstrap/Select2/Selectize CSS (if applicable): can't tell, look in Plunker demo (sorry)

**Comment by CraigJohnson** [comment]
I ran into this problem, too. The fix in [#1824](https://github.com/angular-ui/ui-select/pull/1824) fixes it for me. Just waiting for the next release.

**Comment by Mugi4ok** [comment]
@CraigJohnson, ah, so the culprit is already found, good to hear. Looking forward to the next release then :)

**Comment by Jefiozie** [comment]
Just checking but is this already fixed in the 0.19.5 release?

**Comment by CraigJohnson** [comment]
No, it is not. Until `lockedItems.splice(lockedItemIndex, 0);` is changed to `lockedItems.splice(lockedItemIndex, 1);` ([here](https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L785)), it's not fixed.

**Comment by Jefiozie** [comment]
@CraigJohnson would you mind making a "new" PR for this with some tests. Happy to review.

Thanks

**Comment by CraigJohnson** [comment]
The fix has already been merged — [https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L494](https://github.com/angular-ui/ui-select/blob/master/src/uiSelectController.js#L494) — it just didn't make it into dist — [https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L785](https://github.com/angular-ui/ui-select/blob/master/dist/select.js#L785).

**Comment by Jefiozie** [comment]
Ah I see thanks will add it to the list for the new release.

**Comment by Jefiozie** [comment]
Can be closed now as it is merged.
