### ISSUE TITLE
ng-required not validating form on submit

### ISSUE THREAD

**Issue by mouryaamit** [angular-ui/ui-select#258]
when using ui-select with ng-required or required attribute, form is not validating on submit action.

**Comment by abobwhite** [comment]
@RichardAllen Has your fix been merged?

**Comment by ravishivt** [comment]
+1

**Comment by noetix** [comment]
+1

**Comment by vtortola** [comment]
+1

**Comment by olso** [comment]
+1

**Comment by eliias** [comment]
+1

**Comment by gsf-greece** [comment]
+1

**Comment by dmitrygaraev** [comment]
Multiselect validation doesn't work in 0.9.9

**Comment by yaneq** [comment]
Not working for me either with ui-select 0.9.9 and angular 1.3.11

**Comment by yaneq** [comment]
I fixed it now by adding a custom validator for the multiple ui-select

``` javascript
module.directive('uiSelectRequired', function() {
  return {
    require: 'ngModel',
    link: function(scope, elm, attrs, ctrl) {
      ctrl.$validators.uiSelectRequired = function(modelValue, viewValue) {
        return modelValue && modelValue.length;
      };
    }
  };
});
```

``` slim
// in view
ui-select {
  multiple='true'
  ng-model='something.something'
  ui-select-required
}
```

[Plunkr](http://plnkr.co/edit/vGY70qhMLlpX8mGvHBRP?p=preview)

**Comment by zentetsukenz** [comment]
@yaneq solution almost works for me. The condition `modelValue && modelValue.length;` is not always return true or false, because the `modelValue` sometimes is `undefined`, so I have to check first wether `modelValue` or `viewValue` is an actual array, and finally check its length.

Here's the code
```javascript

app.module.directive('uiSelectRequired', function() {
  return {
    require: 'ngModel',
    link: function(scope, elm, attrs, ctrl) {
      ctrl.$validators.uiSelectRequired = function(modelValue, viewValue) {

        var determineVal;
        if (angular.isArray(modelValue)) {
          determineVal = modelValue;
        } else if (angular.isArray(viewValue)) {
          determineVal = viewValue;
        } else {
          return false;
        }
        
        return determineVal.length > 0;
      };
    }
  };
});
```

This is my markup
```HTML
<ui-select name="items" multiple
  ui-select-required
  ng-model="item.items">
  <ui-select-match>
    {{$item.name}}
  </ui-select-match>
  <ui-select-choices repeat="item in items | filter: $select.search">
    <div ng-bind-html=item.name | highlight: $select.search"></div>
  </ui-select-choices>
</ui-select>
```

And the items list is an array of objects.
```javascript
[
  {id: 1, name: 'item 1'},
  {id: 2, name: 'item 2'},
...
]
```

Anyone care to explain why `modelValue`, `viewValue` sometimes got `undefined` or some random number, would be appreciated.

**Comment by gsf-greece** [comment]
why not use the patch from cc496781adcc85355a3cf9204d2e052d9d8368da ? 
maybe the undefined has to do something with this bug #695? I've been stuck with version 0.9.7 because of this.

**Comment by zentetsukenz** [comment]
@gsf-greece  I try version 0.11.1 and still not working so I go back to version 0.9.9, because, initially, my project use 0.9.9, then use the method posted above and finally got it works. Not sure why cc49678 wasn't fixed for me.

Thanks for your suggestion :)

**Comment by gsf-greece** [comment]
Just an update, 0.11.2 fixes most of the problems I had encountered, so with the patch mentioned above ui-select seems to be working great. Let's hope it will be merged soon! thanks for your great work so far.

**Comment by cmichal** [comment]
Can patch cc49678 be merged to latest? It fixes this issue for me.

**Comment by sergiu-paraschiv** [comment]
Anyone else having an issue with the validation kicking in before user interaction? I don't see any use of `$dirty`, `$touched` or `$pristine` with this directive and `ng-required`.

**Comment by shenlong** [comment]
The patch is not working for ui-select version 0.11.2

**Comment by cmichal** [comment]
Here you have working version:

http://plnkr.co/edit/5Zt0OfEFh18tlcKP1Yen?p=preview

**Comment by shenlong** [comment]
@cmichal , what do you mean by working version?

When you click on the Save button, the validation bubble does not come out. for the ui-select control.

**Comment by cmichal** [comment]
For ui-select you have other required field indicator - it's read border and red label.

**Comment by gdoron** [comment]
@shenlong Did you manage to make the validation work for ui-select on submit?

**Comment by LeleDev** [comment]
temporary workaround: add this directive
```
.directive('arrayRequired',function(){
  return {
    restrict:'A',
    require:'ngModel',
    link:function(scope,elem,attrs,ngModel){

      ngModel.$validators.arrayRequired = function(modelValue,viewValue){
        return (modelValue.length>0 ? true : false);
      };

    }
  };
})
```

add add array-required property to the multiselect that you want to validate

**Comment by JrSchild** [comment]
+1

**Comment by GilbertChan** [comment]
+1

**Comment by f1ght4fun** [comment]
@shenlong did you manage to find solution to have ui-select single/multiple to validate required attribute and show popup like on the simple html5 select ?

**Comment by yaojingguo** [comment]
+1

**Comment by gustavolira** [comment]
+1

**Comment by ricpan** [comment]
+1

**Comment by thinger-io** [comment]
+1

**Comment by fernan256** [comment]
+1

**Comment by samuel-weber** [comment]
+1

**Comment by ezyk** [comment]
+1

**Comment by uguryilmaz** [comment]
+1

**Comment by rmariuzzo** [comment]
:+1:

**Comment by bmustata** [comment]
+1

**Comment by KoenVM** [comment]
+1

**Comment by singhkua** [comment]
+1

**Comment by mukulgupta2507** [comment]
+1

**Comment by mukulgupta2507** [comment]
Can anyone please tell me how can we extend the directive mentioned above to accomodate the checking of validation only when the element is visible ?

P.S. I could have used the patch mentioned in the thread but just don't want to mess up my dependencies in any way.

Thanks

**Comment by LeleDev** [comment]
You could give a try to my 'arrayRequired' directive...

**Comment by mukulgupta2507** [comment]
@LeleDev 

Based on @zentetsukenz solution, I have started using following directive:

```
app.module.directive('uiSelectRequired', function() {
  return {
    require: 'ngModel',
    link: function(scope, elm, attrs, ctrl) {
      ctrl.$validators.uiSelectRequired = function(modelValue, viewValue) {

        var determineVal;
        if (angular.isArray(modelValue)) {
          determineVal = modelValue;
        } else if (angular.isArray(viewValue)) {
          determineVal = viewValue;
        } else {
          return false;
        }

        return determineVal.length > 0;
      };
    }
  };
});
```

There are chances of getting modelValue as undefined and therefore checking both modelValue and viewValue seems to be a better option. I just can't figure out how can I add an additional check if the element is actually visible or hidden on page ?

**Comment by LeleDev** [comment]
Use ng-switch / ng-if instead of ng-show / ng-hide

**Comment by mukulgupta2507** [comment]
@LeleDev 
Thanks a lot. ng-if works like a charm :)

**Comment by Seiifer** [comment]
@zentetsukenz 

I used a much simpler condition but I'm not sure I'm handling every cases :

```javascript
app.directive('uiSelectRequired', function() {
  return {
    require: 'ngModel',
    link: function(scope, elm, attrs, ctrl) {
      ctrl.$validators.uiSelectRequired = function(modelValue, viewValue) {
        if (modelValue && modelValue.length > 0)
          return true;
        return false;
      };
    }
  };
});
```

Is that enough ?

**Comment by zentetsukenz** [comment]
@Seiifer 

Should be ok.

In my case, I'm not sure in what case that the `viewValue` and `modelValue` might be out of sync, so I just make sure it try finding all the possible values.

**Comment by eugeneos** [comment]
+1

**Comment by bharathitman** [comment]
+1

**Comment by rafa-aguilar** [comment]
+1

**Comment by landeeyo** [comment]
+1

**Comment by rodrigocarranza-santex** [comment]
+1

**Comment by MadUser** [comment]
to support expression evaluation I am using this:

```
angular.module("app").directive('uiSelectRequired', function () {
        return {
            require: 'ngModel',
            link: function (scope, element, attr, ctrl) {
                ctrl.$validators.uiSelectRequired = function (modelValue, viewValue) {
                    if (attr.uiSelectRequired) {
                        var isRequired = scope.$eval(attr.uiSelectRequired)
                        if (isRequired == false)
                            return true;
                    }
                    var determineVal;
                    if (angular.isArray(modelValue)) {
                        determineVal = modelValue;
                    } else if (angular.isArray(viewValue)) {
                        determineVal = viewValue;
                    } else {
                        return false;
                    }
                    return determineVal.length > 0;
                };
            }
        };
    });
```

**Comment by stkrwilson** [comment]
This worked for me:

.directive('arrayRequired',function(){
  return {
    restrict:'A',
    require:'ngModel',
    link:function(scope,elem,attrs,ngModel){
      ngModel.$validators.arrayRequired = function(modelValue,viewValue){
      	var modelValue = modelValue || {}
           return (modelValue.length>0 ? true : false);
      };
    }
  };
})

add `array-required` to ui-select object

**Comment by user378230** [comment]
@stkrwilson `ng-required` should work in the latest  version as `ngModel.$isEmpty` is now [correctly overidden](https://github.com/angular-ui/ui-select/blob/cf27a961c6a3e6a6f6f09107c67b11bba7fd3e3c/src/uiSelectMultipleDirective.js#L84) are you able to reproduce the problem in latest version (`v0.17.1`) still?

**Comment by michahell** [comment]
```ng-required``` did not work for me. Another ugly hack is to create a regular text input directly below the ui-select, give it the exact same ng-model and put a ```required``` on that. give it a CSS class that stays visible but that actually hides it.

```
.sg-hack-uiselect {
    line-height: 0.00001;
    height: 0.000001px;
    z-index: -1;
    position: relative;
    bottom: 10px;
    opacity: 0.1;
  }

  .sg-hack-uiselect:focus {
    outline: none;
  }
```

**Comment by zgbjgg** [comment]
Hello guys!, 

I've solved this to use in one of our projects, you can find the library working here:

https://github.com/zgbjgg/ui-select/tree/ng-required

Basically, I did a change to observe the ng-required, and change to false when the model is not empty, otherwise is required (set to true),

I hope this can be helpful

:)

**Comment by randdusing** [comment]
@zgbjgg Can you point us to the changes you made?

**Comment by ohjames** [comment]
@randdusing follow his link, check the commit log, view his commit.
@zgbjgg how about submitting a PR with your change? Although you'll need to alter your indentation style to match the project (`git rebase -i upstream/master && git commit --amend`)

**Comment by ohjames** [comment]
@zgbjgg Ah you modified `dist/select.js` instead of the source files also.

**Comment by ohjames** [comment]
@zgbjgg I cleaned up your commit and made it into a PR, hope you don't mind. I really need this to work ;)

**Comment by ohjames** [comment]
@zgbjgg hm I just tested your changes and they don't work for me.

**Comment by patou** [comment]
I had to the template an hidden input who display the placeholder.
And I had put the ng-required on this input.
With this, the browser block the submit of the form and display a message.

Here my commit :
https://github.com/patou/ui-select/commit/6652d5e676150020b718b88175805c7d2978443a

I don't have time to realy test this new functionality and create a PR.

**Comment by zgbjgg** [comment]
Hello, I am not expert building with the tools provided by gulp for example, but, for a project, I helped to my team to make this work, and using with the code that I modified seems to work perfectly and the ng-required is validated correctly when a form is submitted!

**Comment by JosepAlacid** [comment]
I've just added two conditions more. Now I can use it in single selects.

<code>.directive('uiSelectRequired', function () {
    return {
        require: 'ngModel',
        link: function (scope, element, attr, ctrl) {
            ctrl.$validators.uiSelectRequired = function (modelValue, viewValue) {
                if (attr.uiSelectRequired) {
                    var isRequired = scope.$eval(attr.uiSelectRequired)
                    if (isRequired == false)
                        return true;
                }
                var determineVal;
                if (angular.isArray(modelValue)) {
                    determineVal = modelValue;
                } else if (angular.isArray(viewValue)) {
                    determineVal = viewValue;
                } else if (angular.isObject(modelValue)) {
                    determineVal = angular.equals(modelValue, {}) ? [] : ['true'];
                } else if (angular.isObject(viewValue)) {
                    determineVal = angular.equals(viewValue, {}) ? [] : ['true'];
                } else {
                    return false;
                }
                return determineVal.length > 0;
            };
        }
    };
});</code>

**Comment by doug31415** [comment]
Hey Guys, could simplify this like this, using lodash:

``` ctrl.$validators.uiSelectRequired = function( modelValue, viewValue ) {
        var enabled = !_.isEmpty( modelValue ); // returns false for either {} or [], also for booleans
        return enabled;
      };```

Might be missing something but it seems you wouldnt want to check on the viewValue unless, maybe, you were allowing someone to dynamically add tags, no?

**Comment by vamsikrishnamannem** [comment]
+1

**Comment by s1lviu** [comment]
+100 and thanks @doug31415

**Comment by Jefiozie** [comment]
Please do not "+1" issues, use github 👍 reactions if you really must. Comments should be reserved for constructive discussion/issue resolution. +1s merely add unnecessary noise and scrolling between other, more helpful, replies.

Other ways you can actually help include:

Submitting a pull request that resolves the issue/adds the requested feature
Researching possible implementations or causes of bugs
Providing reproduction plunkrs if one isn't already available

Thanks! 😄

**Comment by doug31415** [comment]
Hi Jeffrey

Actually in our group we use the +1 to indicate a passing review, so its more than just noise. Is there some issue with our doing that on our own teams?

Doug

**Comment by Jefiozie** [comment]
Don't know here it is preferred to do it in the way as described.
Still thanks for sharing your thoughts on this +1 handling.

**Comment by kipusoep** [comment]
Works fine for me...
Versions:
angular: v1.6.7-build.5483+sha.84294ec
angular-ui-select: v0.19.8,
