### ISSUE TITLE
Width of the select when an item with large name is selected (question)

### ISSUE THREAD

**Issue by germanger** [angular-ui/ui-select#933]
This is my ui-select:

```
<ui-select ng-model="selectedReceiver.selected" ng-disabled="fetchingReceivers || receivers.length == 0">
    <ui-select-match placeholder="">{{$select.selected.code}} - {{$select.selected.name}}</ui-select-match>
    <ui-select-choices repeat="receiver in receivers | filterBy: ['name', 'code']: $select.search"> 
        <div ng-bind-html="receiver.name | highlight: $select.search"></div>
        <small>Code: <span ng-bind-html="receiver.code | highlight: $select.search"></span></small>
        <hr style="margin-top: 0px; margin-bottom: 0px; border-top: 1px solid #C0C0C0;"/>
    </ui-select-choices>
</ui-select>
```

When an item is selected, say:

```
     {
           code: "some large code",
           name: "some very large name, foo bar qux"
     }
```

the `ui-select-match` shows "some large code - some very large name, foo bar qux" (as expected), but this is so large that resizes the control (the `<button>` in which the directive is translated).

![visual example](https://cloud.githubusercontent.com/assets/2080549/7671715/922a4c86-fcb0-11e4-921f-4805ba38edd2.png)

Question: Is there a setting for preventing this resize?

**Comment by blowsie** [comment]
Perhaps the use of  `text-overflow: ellipsis;` could be of some use for a fix.
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow#Opera_notes

**Comment by blowsie** [comment]
Its worth looking at the clear selection button in this as well, It also has layout issues.

![image](https://cloud.githubusercontent.com/assets/308572/8033478/86eb2976-0dd6-11e5-87fd-9ef23dcc9067.png)

**Comment by blowsie** [comment]
After just a few lines of css;
![image](https://cloud.githubusercontent.com/assets/308572/8033545/2419e606-0dd7-11e5-9728-edd9960909f4.png)

Code to follow.

**Comment by blowsie** [comment]
Referencing
https://github.com/angular-ui/ui-select/issues/975

**Comment by germanger** [comment]
hummm is not working for me

**Comment by germanger** [comment]
The following just worked for me.

    .ui-select-match-text > span {
        width: 80%;
        overflow: hidden;
        text-overflow: ellipsis;
        position: absolute;
    }

I'm not touching original ui-select css file. This definitions are set after that.
As you can see I'm targeting to the `span` that is inside `.ui-select-match-text`

**Comment by blowsie** [comment]
Perhaps we have a different version, but using `width:80%` is not a good idea. you should opt for padding right instead

**Comment by sumomostudio** [comment]
I am having the same issue.

**Comment by rzschech** [comment]
This is needed for the ui-select-placeholder as well. I have:
```
.ui-select-placeholder, .ui-select-match-text {
  width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 40px;
}
```

**Comment by uguryilmaz** [comment]
@germanger solution worked for me. thanks.

**Comment by wesleycho** [comment]
This is probably best added to the library itself - PRs welcome.

**Comment by Hesesses** [comment]
How to fix this when using `multiple`option?

**Comment by DenisaSurdu** [comment]
@Hesesses , this is how I fixed it: 
```
.ui-select-placeholder, .ui-select-match-text, .ui-select-match-item {
 	max-width: 100%;
	overflow: hidden;
	text-overflow: ellipsis;
	padding-right: 40px;
}
```

**Comment by germanger** [comment]
I've noticed a case in which this solution doesn't work...

Put the ui-select inside an input-group:

                <div class="input-group">
                        
                        <span class="input-group-addon"><a href="" ng-click="selectedItem.selected = undefined" title="Clear"><span class="glyphicon glyphicon-remove"></span></a></span>
                </div>

I typically use these input-groups for optional selection.

Here is a screenshot within and without input-group

![image](https://cloud.githubusercontent.com/assets/2080549/22437150/af156dbc-e705-11e6-8b3e-32e8b36b17f7.png)


...Any help? thanks

**Comment by lacivert** [comment]
I use the theme select2, ui-select doesn't even show the option with large text. I think it also have an issue with the theme selected

**Comment by germanger** [comment]
can this issue be opened? the Plunkr I created shows pretty clear that this is not solved

**Comment by Jefiozie** [comment]
Sure, could you also investigate the issue and maybe make a PR or provide enough information so that somebody can make the PR?

**Comment by halofourteen** [comment]
`input-group` class sets `display: table;` style in bootstrap css. So it's breaks element... Still can't find good solution to fix this.

**Comment by kevinah95** [comment]
@Hesesses another possibility can be:
```
.ui-select-placeholder,.ui-select-match-text,.ui-select-match-item{
  width: 100%;
  overflow: hidden !important;
  text-overflow: ellipsis !important;
  padding-right: 20px;
}


.ui-select-multiple.ui-select-bootstrap .ui-select-match-item{
    width: auto;
    padding-right: 5px;
}
```
to fix label or tag width.

**Comment by harshikesh** [comment]
<ui-select ng-model="selectedReceiver.selected" ng-disabled="fetchingReceivers || receivers.length == 0">
    <ui-select-match placeholder="">{{$select.selected.code}} - {{$select.selected.name}}</ui-select-match>
    <ui-select-choices repeat="receiver in receivers | filterBy: ['name', 'code']: $select.search"> 
        <div ng-bind-html="receiver.name | highlight: $select.search"></div>
        <small>Code: <span ng-bind-html="receiver.code | highlight: $select.search"></span></small>
        <hr style="margin-top: 0px; margin-bottom: 0px; border-top: 1px solid #C0C0C0;"/>
    </ui-select-choices>
</ui-select>

I am using 0.18.1 angular. How to fix the overflow text.
note: I am restricted not to update angular.

**Comment by 578305** [comment]
Using text-overflow: ellipsis; is fine but I want to view the text which is over flowing. How can I do that ? Can we use any tool tip kind of option so that when we hover we can see the whole text?

**Comment by blowsie** [comment]
`title` tag?

**Comment by kartik468** [comment]
> Using text-overflow: ellipsis; is fine but I want to view the text which is over flowing. How can I do that ? Can we use any tool tip kind of option so that when we hover we can see the whole text?

i think you might have to add custom template with title or any tooltip.
By looking at source code, It looks like there is no other solution except to add the custom template.
